# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ci

on:
  push:
    branches: ['prod', 'preprod', 'dev']
  pull_request:
    branches: ['prod', 'preprod', 'dev']

jobs:
  style:
    runs-on: ubuntu-latest


    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.4.x

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_SECRET_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY}}
          aws-region: ${{ secrets.AWS_REGION }}    
      - run: aws codeartifact login --tool npm --repository harena-store --domain npm-hei-school --domain-owner 088312068315 --region eu-west-3


      - name: Install dependencies
        run: npm ci

      - name: Run Prettier check
        run: npm run format:check

      - name: Run Eslint
        run: npm run lint

      - name: Run build
        run: npm run build 
